#include "menu.h"

void menu_init(){
}

void menu_free(){
}

#define MENU_BUTTON_WIDTH 300
#define MENU_BUTTON_HEIGHT 20

u8 menu_update(){
	if(ui_button(1,0.5*(RESX-MENU_BUTTON_WIDTH),RESY*0.25,MENU_BUTTON_WIDTH,MENU_BUTTON_HEIGHT)){
		return STATE_GAME;
	}
	ui_button(2,0.5*(RESX-MENU_BUTTON_WIDTH),RESY*0.25+MENU_BUTTON_HEIGHT*2.0*1,MENU_BUTTON_WIDTH,MENU_BUTTON_HEIGHT);
	ui_button(3,0.5*(RESX-MENU_BUTTON_WIDTH),RESY*0.25+MENU_BUTTON_HEIGHT*2.0*2,MENU_BUTTON_WIDTH,MENU_BUTTON_HEIGHT);
	ui_button(4,0.5*(RESX-MENU_BUTTON_WIDTH),RESY*0.25+MENU_BUTTON_HEIGHT*2.0*3,MENU_BUTTON_WIDTH,MENU_BUTTON_HEIGHT);
	if(ui_button(5,0.5*(RESX-MENU_BUTTON_WIDTH),RESY*0.25+MENU_BUTTON_HEIGHT*2.0*5,MENU_BUTTON_WIDTH,MENU_BUTTON_HEIGHT)){
		return STATE_QUIT;
	}
	ui_update();
	return STATE_MENU;
}

void menu_render(){
	ui_render();
}
